server {
    listen 80;
    listen [::]:80;
    server_name ninjas.loonas.id api.ninjas.loonas.id api.loonas.id app.loonas.id loonas.id;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name loonas.id;

    ssl_certificate     /etc/letsencrypt/live/loonas.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/loonas.id/privkey.pem;

    location / {
        proxy_pass http://loonas_landing:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name api.loonas.id;

    ssl_certificate     /etc/letsencrypt/live/api.loonas.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.loonas.id/privkey.pem;

    client_max_body_size 100m;

    location / {
        proxy_pass http://loonas_api:14000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name app.loonas.id;

    ssl_certificate     /etc/letsencrypt/live/app.loonas.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/app.loonas.id/privkey.pem;

    location / {
        proxy_pass http://loonas_webapp:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name api.ninjas.loonas.id;

    ssl_certificate     /etc/letsencrypt/live/api.ninjas.loonas.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.ninjas.loonas.id/privkey.pem;

    client_max_body_size 100m;

    location / {
        proxy_pass http://loonas_ninjas-api:15000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name ninjas.loonas.id;

    ssl_certificate     /etc/letsencrypt/live/ninjas.loonas.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ninjas.loonas.id/privkey.pem;

    location / {
        proxy_pass http://loonas_ninjas:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}