server {
    listen 80;
    listen [::]:80;
    server_name sancaka-api.monosolusi.com grafana.tokosumatra.monosolusi.com loki.tokosumatra.monosolusi.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name grafana.tokosumatra.monosolusi.com;

    ssl_certificate     /etc/letsencrypt/live/grafana.tokosumatra.monosolusi.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/grafana.tokosumatra.monosolusi.com/privkey.pem;

    location / {
        proxy_pass http://tokosumatra_grafana:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name loki.tokosumatra.monosolusi.com;

    ssl_certificate     /etc/letsencrypt/live/loki.tokosumatra.monosolusi.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/loki.tokosumatra.monosolusi.com/privkey.pem;

    location / {
        proxy_pass http://tokosumatra_loki:3100;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name sancaka-api.monosolusi.com;

    ssl_certificate     /etc/letsencrypt/live/sancaka-api.monosolusi.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sancaka-api.monosolusi.com/privkey.pem;

    location / {
        proxy_pass http://sancaka-api:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}