server {
    listen 80;
    listen [::]:80;
    server_name sancaka-api.monosolusi.com tokosumatra.monosolusi.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name tokosumatra.monosolusi.com;

    ssl_certificate     /etc/letsencrypt/live/tokosumatra.monosolusi.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/tokosumatra.monosolusi.com/privkey.pem;

    location /grafana/ {
        proxy_pass http://tokosumatra_grafana:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        rewrite ^/grafana/(.*) /$1 break;
    }

    location /loki/ {
        proxy_pass http://loki:3100/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Add authentication for Loki
        # auth_basic "Restricted Access";
        # auth_basic_user_file /etc/nginx/.htpasswd;

        rewrite ^/loki(/.*)$ $1 break; # Ensure correct path mapping
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name sancaka-api.monosolusi.com;

    ssl_certificate     /etc/letsencrypt/live/sancaka-api.monosolusi.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sancaka-api.monosolusi.com/privkey.pem;

    location / {
        proxy_pass http://sancaka-api:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}